//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.17 at 01:14:14 PM EST 
//


package com.transitchicago.arrivals;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tmst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="errCd" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="errNm" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="eta" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="staId" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                   &lt;element name="stpId" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                   &lt;element name="staNm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="stpDe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="rn" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                   &lt;element name="rt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="destSt" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                   &lt;element name="destNm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="trDr" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="prdt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="arrT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="isApp" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="isSch" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="isDly" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="isFlt" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="flags" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="lon" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tmst",
    "errCd",
    "errNm",
    "eta"
})
@XmlRootElement(name = "ctatt")
public class TrainArrival {

    @XmlElement(required = true)
    protected String tmst;
    @XmlSchemaType(name = "unsignedByte")
    protected short errCd;
    @XmlElement(required = true)
    protected Object errNm;
    @XmlElement(required = true)
    protected List<TrainArrival.Eta> eta;

    /**
     * Gets the value of the tmst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTmst() {
        return tmst;
    }

    /**
     * Sets the value of the tmst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTmst(String value) {
        this.tmst = value;
    }

    /**
     * Gets the value of the errCd property.
     * 
     */
    public short getErrCd() {
        return errCd;
    }

    /**
     * Sets the value of the errCd property.
     * 
     */
    public void setErrCd(short value) {
        this.errCd = value;
    }

    /**
     * Gets the value of the errNm property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getErrNm() {
        return errNm;
    }

    /**
     * Sets the value of the errNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setErrNm(Object value) {
        this.errNm = value;
    }

    /**
     * Gets the value of the eta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ctatt.Eta }
     * 
     * 
     */
    public List<TrainArrival.Eta> getEta() {
        if (eta == null) {
            eta = new ArrayList<TrainArrival.Eta>();
        }
        return this.eta;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="staId" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="stpId" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="staNm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="stpDe" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="rn" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="rt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="destSt" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="destNm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="trDr" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="prdt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="arrT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="isApp" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="isSch" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="isDly" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="isFlt" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="flags" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="lon" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "staId",
        "stpId",
        "staNm",
        "stpDe",
        "rn",
        "rt",
        "destSt",
        "destNm",
        "trDr",
        "prdt",
        "arrT",
        "isApp",
        "isSch",
        "isDly",
        "isFlt",
        "flags",
        "lat",
        "lon",
        "heading"
    })
    public static class Eta {

        @XmlSchemaType(name = "unsignedShort")
        protected int staId;
        @XmlSchemaType(name = "unsignedShort")
        protected int stpId;
        @XmlElement(required = true)
        protected String staNm;
        @XmlElement(required = true)
        protected String stpDe;
        @XmlSchemaType(name = "unsignedShort")
        protected int rn;
        @XmlElement(required = true)
        protected String rt;
        @XmlSchemaType(name = "unsignedShort")
        protected int destSt;
        @XmlElement(required = true)
        protected String destNm;
        @XmlSchemaType(name = "unsignedByte")
        protected short trDr;
        @XmlElement(required = true)
        protected String prdt;
        @XmlElement(required = true)
        protected String arrT;
        @XmlSchemaType(name = "unsignedByte")
        protected short isApp;
        @XmlSchemaType(name = "unsignedByte")
        protected short isSch;
        @XmlSchemaType(name = "unsignedByte")
        protected short isDly;
        @XmlSchemaType(name = "unsignedByte")
        protected short isFlt;
        @XmlElement(required = true)
        protected String flags;
        @XmlElement(required = true)
        protected BigDecimal lat;
        @XmlElement(required = true)
        protected BigDecimal lon;
        @XmlSchemaType(name = "unsignedShort")
        protected int heading;

        /**
         * Gets the value of the staId property.
         * 
         */
        public int getStaId() {
            return staId;
        }

        /**
         * Sets the value of the staId property.
         * 
         */
        public void setStaId(int value) {
            this.staId = value;
        }

        /**
         * Gets the value of the stpId property.
         * 
         */
        public int getStpId() {
            return stpId;
        }

        /**
         * Sets the value of the stpId property.
         * 
         */
        public void setStpId(int value) {
            this.stpId = value;
        }

        /**
         * Gets the value of the staNm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStaNm() {
            return staNm;
        }

        /**
         * Sets the value of the staNm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStaNm(String value) {
            this.staNm = value;
        }

        /**
         * Gets the value of the stpDe property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStpDe() {
            return stpDe;
        }

        /**
         * Sets the value of the stpDe property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStpDe(String value) {
            this.stpDe = value;
        }

        /**
         * Gets the value of the rn property.
         * 
         */
        public int getRn() {
            return rn;
        }

        /**
         * Sets the value of the rn property.
         * 
         */
        public void setRn(int value) {
            this.rn = value;
        }

        /**
         * Gets the value of the rt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRt() {
            return rt;
        }

        /**
         * Sets the value of the rt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRt(String value) {
            this.rt = value;
        }

        /**
         * Gets the value of the destSt property.
         * 
         */
        public int getDestSt() {
            return destSt;
        }

        /**
         * Sets the value of the destSt property.
         * 
         */
        public void setDestSt(int value) {
            this.destSt = value;
        }

        /**
         * Gets the value of the destNm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestNm() {
            return destNm;
        }

        /**
         * Sets the value of the destNm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestNm(String value) {
            this.destNm = value;
        }

        /**
         * Gets the value of the trDr property.
         * 
         */
        public short getTrDr() {
            return trDr;
        }

        /**
         * Sets the value of the trDr property.
         * 
         */
        public void setTrDr(short value) {
            this.trDr = value;
        }

        /**
         * Gets the value of the prdt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrdt() {
            return prdt;
        }

        /**
         * Sets the value of the prdt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrdt(String value) {
            this.prdt = value;
        }

        /**
         * Gets the value of the arrT property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArrT() {
            return arrT;
        }

        /**
         * Sets the value of the arrT property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArrT(String value) {
            this.arrT = value;
        }

        /**
         * Gets the value of the isApp property.
         * 
         */
        public short getIsApp() {
            return isApp;
        }

        /**
         * Sets the value of the isApp property.
         * 
         */
        public void setIsApp(short value) {
            this.isApp = value;
        }

        /**
         * Gets the value of the isSch property.
         * 
         */
        public short getIsSch() {
            return isSch;
        }

        /**
         * Sets the value of the isSch property.
         * 
         */
        public void setIsSch(short value) {
            this.isSch = value;
        }

        /**
         * Gets the value of the isDly property.
         * 
         */
        public short getIsDly() {
            return isDly;
        }

        /**
         * Sets the value of the isDly property.
         * 
         */
        public void setIsDly(short value) {
            this.isDly = value;
        }

        /**
         * Gets the value of the isFlt property.
         * 
         */
        public short getIsFlt() {
            return isFlt;
        }

        /**
         * Sets the value of the isFlt property.
         * 
         */
        public void setIsFlt(short value) {
            this.isFlt = value;
        }

        /**
         * Gets the value of the flags property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFlags() {
            return flags;
        }

        /**
         * Sets the value of the flags property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFlags(String value) {
            this.flags = value;
        }

        /**
         * Gets the value of the lat property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getLat() {
            return lat;
        }

        /**
         * Sets the value of the lat property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setLat(BigDecimal value) {
            this.lat = value;
        }

        /**
         * Gets the value of the lon property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getLon() {
            return lon;
        }

        /**
         * Sets the value of the lon property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setLon(BigDecimal value) {
            this.lon = value;
        }

        /**
         * Gets the value of the heading property.
         * 
         */
        public int getHeading() {
            return heading;
        }

        /**
         * Sets the value of the heading property.
         * 
         */
        public void setHeading(int value) {
            this.heading = value;
        }

    }

}
